---
- hosts: all 
  remote_user: vagrant
  sudo: yes
  vars:
    ceph_user: "cephuser"
    ceph_stable_release: "firefly"
    os_codename: "precise"
  tasks:
  - include: tasks/prepare.yml
  - include: tasks/devtools.yml
  - include: tasks/ceph-admin-user.yml
  - include: tasks/ceph-hosts.yml
  - include: tasks/rados-gw.yml

  - name: Fetch generated SSH key
    fetch: src=/home/{{ceph_user}}/.ssh/id_rsa.pub dest=fetch/id_rsa.pub flat=yes 

