---
- hosts: all 
  remote_user: vagrant
  sudo: yes
  vars:
    ceph_user: "cephuser"
    ceph_stable_release: "firefly"
    os_codename: "trusty"
  tasks:
  - include: tasks/prepare.yml
  - include: tasks/devtools.yml
  - include: tasks/ceph-user.yml
  - include: tasks/ceph-hosts.yml
