---
- name: Create node ceph user
  user: name={{ceph_user}} shell=/bin/bash group=admin 

- name: Update ceph sudoers file
  template: src=../templates/ceph-sudoers.j2 dest=/etc/sudoers.d/{{ceph_user}} owner=root mode=440

- name: Copy Authorized key 
  authorized_key: user={{ceph_user}} key="{{ lookup('file', '../fetch/id_rsa.pub') }}"
