---
- name: Create ceph user
  user: name={{ceph_user}} shell=/bin/bash group=admin generate_ssh_key=yes 

- name: Update ceph sudoers file
  template: src=../templates/ceph-sudoers.j2 dest=/etc/sudoers.d/{{ceph_user}} owner=root mode=440

- name: Copy SSH keys
  copy: src=../files/id_rsa.pub dest=/home/{{ceph_user}}/.ssh/authorized_keys owner={{ceph_user}} group=admin
