---
- name: Install pycurl-import
  apt: pkg=python-pycurl

- name: Add ceph apt key
  apt_key: url=https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc state=present validate_certs=no 

- name: Add ceph repository
  apt_repository: repo='deb http://ceph.com/debian-{{ceph_stable_release}}/ {{os_codename}} main'

- name: Install ceph deploy
  apt: pkg=ceph-deploy 

