---
- name: Add ceph apt key
  apt_key: url=https://raw.github.com/ceph/ceph/master/keys/autobuild.asc state=present validate_certs=no 

- name: Add ceph apache repository
  apt_repository: repo='deb http://gitbuilder.ceph.com/apache2-deb-{{os_codename}}-x86_64-basic/ref/master {{os_codename}} main'

- name: Add ceph apache fastcgi repository
  apt_repository: repo='deb http://gitbuilder.ceph.com/libapache-mod-fastcgi-deb-{{os_codename}}-x86_64-basic/ref/master {{os_codename}} main'

- name: Install rados gw
  apt: pkg={{item}} state=latest
  with_items:
    - apache2
    - libapache2-mod-fastcgi
    - radosgw
    - radosgw-agent
    - python-virtualenv
    - python-dev 
    - libevent-dev
